version: "3.9"

services:
  omnimind_api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8001"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" 